const mockData = [
  {
    id: 1,
    title: "Technology",
    price: 1387,
    imageURL: "http://dummyimage.com/142x230.png/dddddd/000000",
    brand: "Ideal Flawless",
    productType: 'inner-wear',
  },
  {
    id: 2,
    title: "Consumer Services",
    price: 524,
    imageURL: "http://dummyimage.com/181x167.png/dddddd/000000",
    brand: "XtraCare Antibacterial Hand Cleanse",
    productType: 'top-wear',
  },
  {
    id: 3,
    title: "n/a",
    price: 750,
    imageURL: "http://dummyimage.com/104x147.png/ff4444/ffffff",
    brand: "Hand Wash",
    productType: 'bottom-wear',
  },
  {
    id: 4,
    title: "Consumer Services",
    price: 4355,
    imageURL: "http://dummyimage.com/241x201.png/ff4444/ffffff",
    brand: "Sulfamethoxazole and Trimethoprim",
    productType: 'bottom-wear',
  },
  {
    id: 5,
    title: "n/a",
    price: 1495,
    imageURL: "http://dummyimage.com/182x114.png/ff4444/ffffff",
    brand: "Paclitaxel",
    productType: 'bottomn-wear',
  },
  {
    id: 6,
    title: "Technology",
    price: 143,
    imageURL: "http://dummyimage.com/150x138.png/dddddd/000000",
    brand: "Health Mart anti nausea",
    productType: 'inner-wear',
  },
  {
    id: 7,
    title: "Miscellaneous",
    price: 2354,
    imageURL: "http://dummyimage.com/225x194.png/dddddd/000000",
    brand: "Lisinopril",
    productType: 'bottom-wear',
  },
  {
    id: 8,
    title: "Finance",
    price: 576,
    imageURL: "http://dummyimage.com/218x163.png/cc0000/ffffff",
    brand: "Menorrhagia",
    productType: 'top-wear',
  },
  {
    id: 9,
    title: "Capital Goods",
    price: 3885,
    imageURL: "http://dummyimage.com/172x104.png/ff4444/ffffff",
    brand: "Box Elder",
    productType: 'top-wear',
  },
  {
    id: 10,
    title: "n/a",
    price: 2580,
    imageURL: "http://dummyimage.com/189x144.png/dddddd/000000",
    brand: "Nitroglycerin Transdermal System",
    productType: 'botton-wear',
  },
];


module.exports = mockData;